### ISSUE TITLE
Help with MQs

### ISSUE THREAD

**Issue by Peppershaker** [donnemartin/system-design-primer#322]
Could someone please provide an explanation to the following

Redis is useful as a simple message broker but messages can be lost. (Why lost?)

Amazon SQS is hosted but can have high latency and has the possibility of messages being delivered twice. (Why possibly delivered twice?)

**Comment by riandyrn** [comment]
For SQS it is because internally our message is being sent to multiple servers for redundancy and high availability.

Sometimes one of the server that stores the message copy is unavailable when you issue receive or delete message. When such things happens, the message copy would be still stored at that unavailable server. 

When the server become available again then you issue receive message, you will get that message copy. Thus from your perspective you will get duplicate message.

Actually it is possible to get more duplicate messages, not only twice. AWS only guaranteed `At-Least-Once Delivery` properties for SQS, not `Max-Twice Delivery`. 😂

https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/standard-queues.html#standard-queues-at-least-once-delivery
