### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Hakim-CS** [donnemartin/system-design-primer#850]
As a second year computer science student, Which area of Computer science should i choose ?

**Comment by Jannat-Bhengray** [comment]
You should try different things by yourself, if you can't continue that thing for more than 1 week, just skip it and move to next. I myself tried this like first I started web development course but left in 3 days then trading and then software enginneing, but at last i found that I'm more into data work, so yeh! i chose data science then. hope this will help you:)

**Comment by n-ae** [comment]
@Hakim-CS please notice that creating an issue for systems design guide is not a suitable place request the help you seek. I think your question is better suited for softwareengineering.stackexchange.com or similar.

This issue should be #closed as otherwise it wastes everyone's time as this is not an issue with this particular repository.
